// Generated by CoffeeScript 1.3.3
var Manager,
  __slice = [].slice;

Manager = (function() {

  function Manager(options) {}

  Manager.prototype.register_type = function(type, exts, asset_class) {};

  Manager.prototype.unregister_type = function(type) {};

  Manager.prototype.define_exts = function(type, exts, override) {};

  Manager.prototype.ext_to_type = function(ext) {};

  Manager.prototype.mime_to_type = function(mime) {};

  Manager.prototype.asset_class = function(type) {};

  Manager.prototype.register_load = function(name, fnc) {};

  Manager.prototype.unregister_load = function(name) {};

  Manager.prototype.load = function() {};

  Manager.prototype.exec_load = function() {
    var args, name;
    name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  };

  Manager.prototype.register_storage = function(name, storage_class) {};

  Manager.prototype.use_storage = function(name) {};

  Manager.prototype.unregister_storage = function(name) {};

  Manager.prototype.save = function(stor, asset) {};

  Manager.prototype.upsert = function(stor, asset) {};

  Manager.prototype.create = function(stor, asset) {};

  Manager.prototype.read = function(ref) {};

  Manager.prototype.update = function(ref, asset) {};

  Manager.prototype["delete"] = function(ref) {};

  Manager.prototype.exists = function(stor, asset) {};

  return Manager;

})();

module.exports = Manager;
