// Generated by CoffeeScript 1.3.3
var Asset, BufferAsset, types, _,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Asset = require('../asset').Asset;

_ = require('underscore');

BufferAsset = (function(_super) {

  __extends(BufferAsset, _super);

  function BufferAsset() {
    BufferAsset.__super__.constructor.apply(this, arguments);
  }

  BufferAsset.prototype.compile = function() {
    return this.toBuffer();
  };

  return BufferAsset;

})(Asset);

types = {
  "image": ["png", "gif", "jpg", "jpeg"]
};

module.exports = function(manager) {
  return _.each(types, function(exts, type) {
    return manager.register_type(type, exts, BufferAsset);
  });
};
