// Generated by CoffeeScript 1.3.3
(function() {
  var types, _;

  _ = require('underscore');

  types = {
    "text": ["txt", "text"],
    "css": ["css"],
    "javascript": ["js"]
  };

  module.exports = function(manager) {
    return _.each(types, function(exts, type) {
      return manager.register_type(type, exts);
    });
  };

}).call(this);
