// Generated by CoffeeScript 1.3.3
var mime, path, _,
  __slice = [].slice;

mime = require('mime');

_ = require('underscore');

path = require('path');

module.exports = function() {
  return [
    "compile", 100, function() {
      var aobj, args, asset, content, name, next, options, type, _i, _ref;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), next = arguments[_i++];
      aobj = args[0];
      if (!_.isObject(aobj)) {
        return next();
      }
      if (!(_.isString(aobj.name) && aobj.name && Buffer.isBuffer(aobj.content))) {
        return next();
      }
      name = aobj.name;
      content = aobj.content;
      type = aobj.type ? aobj.type : (_ref = this.ext_to_type(path.extname(name).substr(1))) != null ? _ref : "text";
      options = _.isObject(aobj.options) ? aobj.options : {};
      asset = this.new_asset(type, name, options);
      asset.write(content);
      _.defaults(asset, aobj);
      return next(asset);
    }
  ];
};
